// ISO country → cities for /sign-up-collab's location question, biggest /
// most-shot first. The first 3 become the chips; the next up to 3 become the
// "Or type another place — e.g. …" examples. When detection fails or the
// country isn't listed, both come back empty and the form shows no chips
// and a generic placeholder — never another country's cities.

const COUNTRY_CITIES: Record<string, string[]> = {
  // Americas
  US: ['New York', 'Los Angeles', 'Chicago', 'Miami', 'San Francisco', 'Austin'],
  CA: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Quebec City'],
  MX: ['Mexico City', 'Guadalajara', 'Cancún', 'Monterrey', 'Oaxaca', 'Tulum'],
  GT: ['Guatemala City', 'Antigua', 'Quetzaltenango', 'Flores'],
  CR: ['San José', 'Tamarindo', 'La Fortuna', 'Santa Teresa'],
  PA: ['Panama City', 'Bocas del Toro', 'Boquete'],
  CU: ['Havana', 'Trinidad', 'Varadero'],
  DO: ['Santo Domingo', 'Punta Cana', 'Santiago', 'Puerto Plata'],
  PR: ['San Juan', 'Ponce', 'Rincón'],
  JM: ['Kingston', 'Montego Bay', 'Ocho Rios', 'Negril'],
  CO: ['Bogotá', 'Medellín', 'Cartagena', 'Cali', 'Santa Marta', 'Barranquilla'],
  VE: ['Caracas', 'Maracaibo', 'Valencia'],
  EC: ['Quito', 'Guayaquil', 'Cuenca', 'Baños'],
  PE: ['Lima', 'Cusco', 'Arequipa', 'Trujillo', 'Iquitos'],
  BO: ['La Paz', 'Santa Cruz', 'Sucre', 'Cochabamba'],
  BR: ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Belo Horizonte', 'Fortaleza', 'Florianópolis'],
  PY: ['Asunción', 'Ciudad del Este', 'Encarnación'],
  UY: ['Montevideo', 'Punta del Este', 'Colonia'],
  AR: ['Buenos Aires', 'Córdoba', 'Mendoza', 'Rosario', 'Bariloche', 'Salta'],
  CL: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Pucón'],
  // Europe
  GB: ['London', 'Manchester', 'Edinburgh', 'Birmingham', 'Glasgow', 'Bristol'],
  IE: ['Dublin', 'Cork', 'Galway', 'Limerick', 'Kilkenny'],
  FR: ['Paris', 'Lyon', 'Marseille', 'Nice', 'Bordeaux', 'Toulouse'],
  DE: ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt', 'Leipzig'],
  ES: ['Madrid', 'Barcelona', 'Seville', 'Valencia', 'Málaga', 'Bilbao'],
  PT: ['Lisbon', 'Porto', 'Faro', 'Braga', 'Coimbra'],
  IT: ['Rome', 'Milan', 'Florence', 'Naples', 'Venice', 'Turin'],
  NL: ['Amsterdam', 'Rotterdam', 'Utrecht', 'The Hague', 'Eindhoven'],
  BE: ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liège'],
  CH: ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Lucerne'],
  AT: ['Vienna', 'Salzburg', 'Graz', 'Innsbruck', 'Linz'],
  CZ: ['Prague', 'Brno', 'Ostrava', 'Český Krumlov'],
  PL: ['Warsaw', 'Kraków', 'Gdańsk', 'Wrocław', 'Poznań', 'Łódź'],
  SK: ['Bratislava', 'Košice'],
  SI: ['Ljubljana', 'Maribor', 'Bled'],
  HU: ['Budapest', 'Debrecen', 'Szeged'],
  GR: ['Athens', 'Thessaloniki', 'Santorini', 'Mykonos', 'Heraklion', 'Rhodes'],
  RO: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Brașov', 'Iași'],
  BG: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'],
  RS: ['Belgrade', 'Novi Sad', 'Niš'],
  HR: ['Zagreb', 'Split', 'Dubrovnik', 'Zadar', 'Rijeka'],
  BA: ['Sarajevo', 'Mostar', 'Banja Luka'],
  AL: ['Tirana', 'Sarandë', 'Shkodër'],
  MK: ['Skopje', 'Ohrid'],
  SE: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Lund'],
  NO: ['Oslo', 'Bergen', 'Trondheim', 'Tromsø', 'Stavanger'],
  DK: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'],
  FI: ['Helsinki', 'Tampere', 'Turku', 'Rovaniemi'],
  IS: ['Reykjavik', 'Akureyri', 'Vík'],
  EE: ['Tallinn', 'Tartu', 'Pärnu'],
  LV: ['Riga', 'Jūrmala', 'Liepāja'],
  LT: ['Vilnius', 'Kaunas', 'Klaipėda'],
  UA: ['Kyiv', 'Lviv', 'Odesa', 'Kharkiv', 'Dnipro'],
  BY: ['Minsk', 'Brest', 'Grodno'],
  MD: ['Chișinău', 'Bălți'],
  RU: ['Moscow', 'Saint Petersburg', 'Kazan', 'Sochi', 'Novosibirsk'],
  MT: ['Valletta', 'Sliema', 'Mdina'],
  CY: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'],
  TR: ['Istanbul', 'Ankara', 'Izmir', 'Antalya', 'Cappadocia', 'Bursa'],
  // Middle East & Central Asia
  AE: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah'],
  SA: ['Riyadh', 'Jeddah', 'Dammam', 'AlUla'],
  QA: ['Doha'],
  KW: ['Kuwait City'],
  BH: ['Manama'],
  OM: ['Muscat', 'Salalah', 'Nizwa'],
  JO: ['Amman', 'Aqaba', 'Petra', 'Irbid'],
  LB: ['Beirut', 'Tripoli', 'Byblos'],
  IL: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Eilat', 'Nazareth'],
  IR: ['Tehran', 'Isfahan', 'Shiraz', 'Mashhad'],
  IQ: ['Baghdad', 'Erbil', 'Basra'],
  GE: ['Tbilisi', 'Batumi', 'Kutaisi', 'Kazbegi'],
  AM: ['Yerevan', 'Gyumri', 'Dilijan'],
  AZ: ['Baku', 'Ganja', 'Gabala'],
  KZ: ['Almaty', 'Astana', 'Shymkent', 'Aktau'],
  UZ: ['Tashkent', 'Samarkand', 'Bukhara', 'Khiva', 'Fergana'],
  KG: ['Bishkek', 'Osh', 'Karakol'],
  TJ: ['Dushanbe', 'Khujand'],
  TM: ['Ashgabat'],
  AF: ['Kabul', 'Herat', 'Mazar-i-Sharif'],
  // South Asia
  IN: ['Goa', 'Mumbai', 'Delhi', 'Bangalore', 'Jaipur', 'Hyderabad'],
  PK: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad'],
  BD: ['Dhaka', 'Chittagong', 'Sylhet', "Cox's Bazar"],
  LK: ['Colombo', 'Kandy', 'Galle', 'Ella', 'Negombo'],
  NP: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Chitwan'],
  MV: ['Malé'],
  // Southeast & East Asia
  TH: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Krabi', 'Koh Samui'],
  VN: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hoi An', 'Nha Trang', 'Hue'],
  KH: ['Phnom Penh', 'Siem Reap', 'Sihanoukville', 'Kampot'],
  LA: ['Vientiane', 'Luang Prabang', 'Vang Vieng', 'Pakse'],
  MM: ['Yangon', 'Mandalay', 'Bagan', 'Naypyidaw'],
  MY: ['Kuala Lumpur', 'Penang', 'Johor Bahru', 'Malacca', 'Ipoh', 'Kota Kinabalu'],
  SG: ['Singapore'],
  ID: ['Bali', 'Jakarta', 'Yogyakarta', 'Bandung', 'Surabaya', 'Lombok'],
  PH: ['Manila', 'Cebu', 'Davao', 'Palawan', 'Boracay', 'Siargao'],
  CN: ['Shanghai', 'Beijing', 'Shenzhen', 'Guangzhou', 'Chengdu', 'Hangzhou'],
  HK: ['Hong Kong'],
  MO: ['Macau'],
  TW: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hualien'],
  JP: ['Tokyo', 'Osaka', 'Kyoto', 'Fukuoka', 'Sapporo', 'Nagoya'],
  KR: ['Seoul', 'Busan', 'Jeju', 'Incheon', 'Daegu', 'Gyeongju'],
  MN: ['Ulaanbaatar', 'Erdenet', 'Darkhan'],
  // Africa
  EG: ['Cairo', 'Alexandria', 'Giza', 'Luxor', 'Aswan', 'Hurghada'],
  MA: ['Marrakech', 'Casablanca', 'Fes', 'Rabat', 'Tangier', 'Chefchaouen'],
  TN: ['Tunis', 'Sousse', 'Sfax'],
  DZ: ['Algiers', 'Oran', 'Constantine'],
  NG: ['Lagos', 'Abuja', 'Port Harcourt', 'Ibadan', 'Kano'],
  GH: ['Accra', 'Kumasi', 'Cape Coast'],
  SN: ['Dakar', 'Saint-Louis', 'Thiès'],
  CI: ['Abidjan', 'Yamoussoukro', 'Bouaké'],
  CM: ['Douala', 'Yaoundé', 'Bamenda', 'Kribi'],
  ET: ['Addis Ababa', 'Dire Dawa', 'Lalibela'],
  KE: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Diani'],
  TZ: ['Dar es Salaam', 'Zanzibar', 'Arusha', 'Dodoma', 'Moshi'],
  UG: ['Kampala', 'Entebbe', 'Jinja'],
  RW: ['Kigali', 'Musanze', 'Gisenyi'],
  ZM: ['Lusaka', 'Livingstone', 'Ndola'],
  ZW: ['Harare', 'Bulawayo', 'Victoria Falls'],
  MZ: ['Maputo', 'Beira', 'Tofo'],
  NA: ['Windhoek', 'Swakopmund', 'Walvis Bay'],
  BW: ['Gaborone', 'Maun', 'Francistown'],
  ZA: ['Cape Town', 'Johannesburg', 'Durban', 'Pretoria', 'Stellenbosch', 'Port Elizabeth'],
  MU: ['Port Louis', 'Grand Baie', 'Flic en Flac'],
  MG: ['Antananarivo', 'Nosy Be', 'Toamasina'],
  // Oceania
  AU: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Gold Coast', 'Adelaide'],
  NZ: ['Auckland', 'Wellington', 'Christchurch', 'Queenstown', 'Rotorua'],
  FJ: ['Suva', 'Nadi', 'Lautoka'],
}

export function cityChipsForCountry(iso: string | null | undefined): string[] {
  return iso ? (COUNTRY_CITIES[iso] || []).slice(0, 3) : []
}

// The cities after the chips. A single leftover city reads oddly after
// "e.g." and city-states have none, so anything under 2 means no examples.
export function cityExamplesForCountry(iso: string | null | undefined): string[] {
  const extras = iso ? (COUNTRY_CITIES[iso] || []).slice(3, 6) : []
  return extras.length >= 2 ? extras : []
}
