// ISO country → the location chips shown on /sign-up-collab, biggest /
// most-shot cities first, 3 max. Countries not listed fall back to the
// global default set.
export const DEFAULT_CITY_CHIPS = ['New York', 'Istanbul', 'Bangkok']

const COUNTRY_CITIES: Record<string, string[]> = {
  // Americas
  US: ['New York', 'Los Angeles', 'Chicago'],
  CA: ['Toronto', 'Vancouver', 'Montreal'],
  MX: ['Mexico City', 'Guadalajara', 'Cancún'],
  GT: ['Guatemala City', 'Antigua'],
  CR: ['San José', 'Tamarindo'],
  PA: ['Panama City'],
  CU: ['Havana'],
  DO: ['Santo Domingo', 'Punta Cana'],
  PR: ['San Juan'],
  JM: ['Kingston', 'Montego Bay'],
  CO: ['Bogotá', 'Medellín', 'Cartagena'],
  VE: ['Caracas'],
  EC: ['Quito', 'Guayaquil'],
  PE: ['Lima', 'Cusco', 'Arequipa'],
  BO: ['La Paz', 'Santa Cruz'],
  BR: ['São Paulo', 'Rio de Janeiro', 'Salvador'],
  PY: ['Asunción'],
  UY: ['Montevideo'],
  AR: ['Buenos Aires', 'Córdoba', 'Mendoza'],
  CL: ['Santiago', 'Valparaíso'],
  // Europe
  GB: ['London', 'Manchester', 'Edinburgh'],
  IE: ['Dublin', 'Cork', 'Galway'],
  FR: ['Paris', 'Lyon', 'Marseille'],
  DE: ['Berlin', 'Munich', 'Hamburg'],
  ES: ['Madrid', 'Barcelona', 'Seville'],
  PT: ['Lisbon', 'Porto'],
  IT: ['Rome', 'Milan', 'Florence'],
  NL: ['Amsterdam', 'Rotterdam', 'Utrecht'],
  BE: ['Brussels', 'Antwerp', 'Ghent'],
  CH: ['Zurich', 'Geneva', 'Basel'],
  AT: ['Vienna', 'Salzburg', 'Graz'],
  CZ: ['Prague', 'Brno'],
  PL: ['Warsaw', 'Kraków', 'Gdańsk'],
  SK: ['Bratislava'],
  SI: ['Ljubljana'],
  HU: ['Budapest'],
  GR: ['Athens', 'Thessaloniki', 'Santorini'],
  RO: ['Bucharest', 'Cluj-Napoca'],
  BG: ['Sofia', 'Plovdiv'],
  RS: ['Belgrade', 'Novi Sad'],
  HR: ['Zagreb', 'Split', 'Dubrovnik'],
  BA: ['Sarajevo', 'Mostar'],
  AL: ['Tirana'],
  MK: ['Skopje'],
  SE: ['Stockholm', 'Gothenburg', 'Malmö'],
  NO: ['Oslo', 'Bergen'],
  DK: ['Copenhagen', 'Aarhus'],
  FI: ['Helsinki'],
  IS: ['Reykjavik'],
  EE: ['Tallinn'],
  LV: ['Riga'],
  LT: ['Vilnius'],
  UA: ['Kyiv', 'Lviv', 'Odesa'],
  BY: ['Minsk'],
  MD: ['Chișinău'],
  RU: ['Moscow', 'Saint Petersburg'],
  MT: ['Valletta'],
  CY: ['Nicosia', 'Limassol'],
  TR: ['Istanbul', 'Ankara', 'Izmir'],
  // Middle East & Central Asia
  AE: ['Dubai', 'Abu Dhabi', 'Sharjah'],
  SA: ['Riyadh', 'Jeddah'],
  QA: ['Doha'],
  KW: ['Kuwait City'],
  BH: ['Manama'],
  OM: ['Muscat'],
  JO: ['Amman', 'Aqaba'],
  LB: ['Beirut'],
  IL: ['Tel Aviv', 'Jerusalem', 'Haifa'],
  IR: ['Tehran'],
  IQ: ['Baghdad'],
  GE: ['Tbilisi', 'Batumi'],
  AM: ['Yerevan'],
  AZ: ['Baku'],
  KZ: ['Almaty', 'Astana'],
  UZ: ['Tashkent', 'Samarkand', 'Bukhara'],
  KG: ['Bishkek'],
  TJ: ['Dushanbe'],
  TM: ['Ashgabat'],
  AF: ['Kabul'],
  // South Asia
  IN: ['Mumbai', 'Delhi', 'Bangalore'],
  PK: ['Karachi', 'Lahore', 'Islamabad'],
  BD: ['Dhaka', 'Chittagong'],
  LK: ['Colombo', 'Kandy', 'Galle'],
  NP: ['Kathmandu', 'Pokhara'],
  MV: ['Malé'],
  // Southeast & East Asia
  TH: ['Bangkok', 'Chiang Mai', 'Phuket'],
  VN: ['Ho Chi Minh City', 'Hanoi', 'Da Nang'],
  KH: ['Phnom Penh', 'Siem Reap'],
  LA: ['Vientiane', 'Luang Prabang'],
  MM: ['Yangon', 'Mandalay'],
  MY: ['Kuala Lumpur', 'Penang', 'Johor Bahru'],
  SG: ['Singapore'],
  ID: ['Bali', 'Jakarta', 'Yogyakarta'],
  PH: ['Manila', 'Cebu', 'Davao'],
  CN: ['Shanghai', 'Beijing', 'Shenzhen'],
  HK: ['Hong Kong'],
  MO: ['Macau'],
  TW: ['Taipei', 'Kaohsiung', 'Taichung'],
  JP: ['Tokyo', 'Osaka', 'Kyoto'],
  KR: ['Seoul', 'Busan', 'Jeju'],
  MN: ['Ulaanbaatar'],
  // Africa
  EG: ['Cairo', 'Alexandria', 'Giza'],
  MA: ['Marrakech', 'Casablanca', 'Fes'],
  TN: ['Tunis'],
  DZ: ['Algiers'],
  NG: ['Lagos', 'Abuja'],
  GH: ['Accra'],
  SN: ['Dakar'],
  CI: ['Abidjan'],
  CM: ['Douala', 'Yaoundé'],
  ET: ['Addis Ababa'],
  KE: ['Nairobi', 'Mombasa'],
  TZ: ['Dar es Salaam', 'Zanzibar'],
  UG: ['Kampala'],
  RW: ['Kigali'],
  ZM: ['Lusaka'],
  ZW: ['Harare'],
  MZ: ['Maputo'],
  NA: ['Windhoek'],
  BW: ['Gaborone'],
  ZA: ['Cape Town', 'Johannesburg', 'Durban'],
  MU: ['Port Louis'],
  MG: ['Antananarivo'],
  // Oceania
  AU: ['Sydney', 'Melbourne', 'Brisbane'],
  NZ: ['Auckland', 'Wellington', 'Christchurch'],
  FJ: ['Suva'],
}

export function cityChipsForCountry(iso: string | null | undefined): string[] {
  return (iso && COUNTRY_CITIES[iso]) || DEFAULT_CITY_CHIPS
}
