// Paths into the photographic wardrobe catalog. Files are generated by
// scripts/generate-wardrobe.mjs as {pieceId}--{colorwaySlug}.jpg
import type { Piece } from '@/components/wardrobe/contract'

export const colorwaySlug = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-')

export function pieceImage(piece: Piece, hex: string): string {
  const cw = piece.colorways.find(c => c.hex === hex) ?? piece.colorways[0]
  return `/images/wardrobe/${piece.id}--${colorwaySlug(cw.name)}.jpg`
}
