import { chromium } from 'playwright'
import { fileURLToPath } from 'url'
import path from 'path'
import fs from 'fs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, '../../..')
const IMAGE_DIR = path.join(REPO_ROOT, 'public/images/large')
const OUT_DIR = path.join(__dirname, 'output-33d')

const WIDTH = 1080
const HEIGHT = 1920
const SAFE_BOTTOM = 430
const SAFE_TOP = 213
const SAFE_LEFT = 66
const SAFE_RIGHT = 1027

const TOTAL_DURATION_MS = 30000

const MONO = "'SF Mono', 'Menlo', 'Courier New', monospace"

const PROOF_PHOTOS = [
  'manila-gallery-dsc-0190.jpg',
  'manila-gallery-night-001.jpg',
  'manila-gallery-garden-001.jpg',
  'manila-gallery-urban-001.jpg',
  'manila-gallery-canal-001.jpg',
  'manila-gallery-ivy-001.jpg',
  'manila-gallery-closeup-001.jpg',
  'manila-gallery-dsc-0911.jpg',
]

function resetOutputDir() {
  fs.rmSync(OUT_DIR, { recursive: true, force: true })
  fs.mkdirSync(OUT_DIR, { recursive: true })
}

function readImage(name) {
  const buf = fs.readFileSync(path.join(IMAGE_DIR, name))
  return 'data:image/jpeg;base64,' + buf.toString('base64')
}

function writeSources(payload) {
  fs.writeFileSync(path.join(OUT_DIR, 'sources.json'), JSON.stringify(payload, null, 2))
}

/* ──────────────────────────────────────────────────────────────
   Build full HTML — ALL animation is CSS @keyframes + setTimeout
   NO requestAnimationFrame, NO canvas, NO game loops
   ZOOMED IN — blocks are 120px, everything close-up 1:1 pixel scale
   v33d: slower photos (~1.5s), bigger title (66px), bigger blocks (120px)
   ────────────────────────────────────────────────────────────── */
function buildHTML(imageDataMap) {
  const photoSrcs = JSON.stringify(PROOF_PHOTOS.map(function(p) { return imageDataMap[p]; }))

  const GROUND_HEIGHT = 320
  const BRICK_SIZE = 80
  const PIPE_W = 200
  const BLOCK_SIZE = 120

  const WORLD_W = 8000

  // Photo timing: 8 photos spaced 1900ms apart starting at 4s
  // Each photo lingers 1500ms before shrinking
  var photoTimesArr = [];
  for (var pi = 0; pi < 8; pi++) {
    photoTimesArr.push(4000 + pi * 1900);
  }
  var photoTimesJSON = JSON.stringify(photoTimesArr);

  // Scene 3 starts after last photo finishes: 4000 + 7*1900 + 1500 + 400 = ~19200
  var scene3Start = 19200;
  // Scene 4 starts at scene3Start + 5200 = ~24400
  var scene4Start = scene3Start + 5200;

  return '<!DOCTYPE html>\n'
    + '<html>\n<head>\n<style>\n'
    + '  * { box-sizing: border-box; margin: 0; padding: 0; }\n'
    + '  html, body {\n'
    + '    margin: 0; padding: 0;\n'
    + '    background: #5c94fc;\n'
    + '    font-family: ' + MONO + ';\n'
    + '    overflow: hidden;\n'
    + '    width: ' + WIDTH + 'px;\n'
    + '    height: ' + HEIGHT + 'px;\n'
    + '  }\n'
    + '\n'
    + '  #root {\n'
    + '    width: ' + WIDTH + 'px;\n'
    + '    height: ' + HEIGHT + 'px;\n'
    + '    position: relative;\n'
    + '    overflow: hidden;\n'
    + '    background: #5c94fc;\n'
    + '  }\n'
    + '\n'
    + '  /* WORLD CONTAINER — scrolls left like Mario running right */\n'
    + '  #world {\n'
    + '    position: absolute;\n'
    + '    top: 0;\n'
    + '    left: 0;\n'
    + '    width: ' + WORLD_W + 'px;\n'
    + '    height: ' + HEIGHT + 'px;\n'
    + '    animation: worldScroll 16s linear forwards;\n'
    + '    will-change: transform;\n'
    + '  }\n'
    + '\n'
    + '  @keyframes worldScroll {\n'
    + '    0%   { transform: translateX(0); }\n'
    + '    100% { transform: translateX(-' + (WORLD_W - WIDTH) + 'px); }\n'
    + '  }\n'
    + '\n'
    + '  /* GROUND — big chunky bricks */\n'
    + '  #ground {\n'
    + '    position: absolute;\n'
    + '    bottom: 0;\n'
    + '    left: 0;\n'
    + '    width: ' + WORLD_W + 'px;\n'
    + '    height: ' + GROUND_HEIGHT + 'px;\n'
    + '    display: flex;\n'
    + '    flex-wrap: wrap;\n'
    + '    z-index: 5;\n'
    + '  }\n'
    + '  .brick {\n'
    + '    width: ' + BRICK_SIZE + 'px;\n'
    + '    height: ' + BRICK_SIZE + 'px;\n'
    + '    background: #c84c0c;\n'
    + '    border: 4px solid #e8a060;\n'
    + '    border-top-color: #f8d8b0;\n'
    + '    border-left-color: #f8d8b0;\n'
    + '    border-bottom-color: #703010;\n'
    + '    border-right-color: #703010;\n'
    + '    flex-shrink: 0;\n'
    + '  }\n'
    + '  .brick::before {\n'
    + '    content: "";\n'
    + '    display: block;\n'
    + '    width: 100%;\n'
    + '    height: 50%;\n'
    + '    border-bottom: 3px solid #703010;\n'
    + '    box-sizing: border-box;\n'
    + '  }\n'
    + '  .brick::after {\n'
    + '    content: "";\n'
    + '    display: block;\n'
    + '    width: 50%;\n'
    + '    height: 50%;\n'
    + '    border-right: 3px solid #703010;\n'
    + '    box-sizing: border-box;\n'
    + '  }\n'
    + '\n'
    + '  /* PIPE */\n'
    + '  .pipe {\n'
    + '    position: absolute;\n'
    + '    z-index: 6;\n'
    + '  }\n'
    + '  .pipe-rim {\n'
    + '    width: ' + PIPE_W + 'px;\n'
    + '    height: 60px;\n'
    + '    background: #00a800;\n'
    + '    border: 6px solid #005800;\n'
    + '    border-top-color: #80f880;\n'
    + '    border-left-color: #80f880;\n'
    + '  }\n'
    + '  .pipe-rim::before {\n'
    + '    content: "";\n'
    + '    display: block;\n'
    + '    position: absolute;\n'
    + '    top: 10px;\n'
    + '    left: 20px;\n'
    + '    width: 40px;\n'
    + '    height: 40px;\n'
    + '    background: rgba(255,255,255,0.12);\n'
    + '    border-radius: 0;\n'
    + '  }\n'
    + '  .pipe-body-part {\n'
    + '    width: ' + (PIPE_W - 40) + 'px;\n'
    + '    background: #00a800;\n'
    + '    border: 6px solid #005800;\n'
    + '    border-left-color: #80f880;\n'
    + '    margin-left: 20px;\n'
    + '  }\n'
    + '  .pipe-body-part::before {\n'
    + '    content: "";\n'
    + '    display: block;\n'
    + '    width: 16px;\n'
    + '    height: 100%;\n'
    + '    background: rgba(255,255,255,0.1);\n'
    + '    margin-left: 10px;\n'
    + '  }\n'
    + '\n'
    + '  /* QUESTION BLOCK — bigger 120px */\n'
    + '  .qblock {\n'
    + '    width: ' + BLOCK_SIZE + 'px;\n'
    + '    height: ' + BLOCK_SIZE + 'px;\n'
    + '    background: #FAA005;\n'
    + '    border: 8px solid #f8d878;\n'
    + '    border-bottom-color: #885808;\n'
    + '    border-right-color: #885808;\n'
    + '    display: flex;\n'
    + '    align-items: center;\n'
    + '    justify-content: center;\n'
    + '    font-size: 72px;\n'
    + '    font-weight: 900;\n'
    + '    color: #fff;\n'
    + '    text-shadow: 4px 4px 0 #885808;\n'
    + '    font-family: ' + MONO + ';\n'
    + '    position: absolute;\n'
    + '    z-index: 8;\n'
    + '  }\n'
    + '  .qblock::before {\n'
    + '    content: "";\n'
    + '    position: absolute;\n'
    + '    inset: 6px;\n'
    + '    border: 4px solid #c87800;\n'
    + '    pointer-events: none;\n'
    + '  }\n'
    + '  .qblock.used {\n'
    + '    background: #885808;\n'
    + '    border-color: #6a4408;\n'
    + '    color: transparent;\n'
    + '    text-shadow: none;\n'
    + '  }\n'
    + '  .qblock.used::before {\n'
    + '    border-color: #5a3808;\n'
    + '  }\n'
    + '  .qblock.bounce {\n'
    + '    animation: blockBounce 0.4s ease-out;\n'
    + '  }\n'
    + '\n'
    + '  /* CLOUD */\n'
    + '  .cloud {\n'
    + '    position: absolute;\n'
    + '    z-index: 1;\n'
    + '  }\n'
    + '\n'
    + '  /* BUSH */\n'
    + '  .bush {\n'
    + '    position: absolute;\n'
    + '    z-index: 4;\n'
    + '  }\n'
    + '  .bush-body {\n'
    + '    background: #00a800;\n'
    + '    border-radius: 50%;\n'
    + '    position: absolute;\n'
    + '  }\n'
    + '\n'
    + '  /* KEYFRAME ANIMATIONS */\n'
    + '\n'
    + '  @keyframes blockBounce {\n'
    + '    0%   { transform: translateY(0); }\n'
    + '    30%  { transform: translateY(-30px); }\n'
    + '    60%  { transform: translateY(0); }\n'
    + '    80%  { transform: translateY(-12px); }\n'
    + '    100% { transform: translateY(0); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes coinPop {\n'
    + '    0%   { opacity: 1; transform: translateY(0) scaleX(1); }\n'
    + '    25%  { opacity: 1; transform: translateY(-120px) scaleX(0.3); }\n'
    + '    50%  { opacity: 1; transform: translateY(-160px) scaleX(1); }\n'
    + '    75%  { opacity: 0.7; transform: translateY(-120px) scaleX(0.3); }\n'
    + '    100% { opacity: 0; transform: translateY(-80px) scaleX(1); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes fadeIn {\n'
    + '    from { opacity: 0; }\n'
    + '    to   { opacity: 1; }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes slideUp {\n'
    + '    from { opacity: 0; transform: translateY(60px); }\n'
    + '    to   { opacity: 1; transform: translateY(0); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes slideDown {\n'
    + '    from { opacity: 0; transform: translateY(-50px); }\n'
    + '    to   { opacity: 1; transform: translateY(0); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes popIn {\n'
    + '    0%   { opacity: 0; transform: scale(0.3); }\n'
    + '    60%  { opacity: 1; transform: scale(1.1); }\n'
    + '    100% { opacity: 1; transform: scale(1); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes photoExpand {\n'
    + '    0%   { opacity: 0; transform: scale(0) translateY(-40px); }\n'
    + '    50%  { opacity: 1; transform: scale(1.05) translateY(-20px); }\n'
    + '    100% { opacity: 1; transform: scale(1) translateY(0); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes photoShrink {\n'
    + '    0%   { opacity: 1; transform: scale(1); }\n'
    + '    100% { opacity: 0; transform: scale(0.3) translateY(40px); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes starPulse {\n'
    + '    0%, 100% { opacity: 1; transform: scale(1); }\n'
    + '    50%      { opacity: 0.5; transform: scale(1.15); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes flashBig {\n'
    + '    0%   { opacity: 0; transform: scale(1.4); }\n'
    + '    40%  { opacity: 1; transform: scale(0.95); }\n'
    + '    100% { opacity: 1; transform: scale(1); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes powerUpRise {\n'
    + '    0%   { transform: translateY(100px); opacity: 0; }\n'
    + '    30%  { opacity: 1; }\n'
    + '    100% { transform: translateY(0); opacity: 1; }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes coinSpin {\n'
    + '    0%   { transform: scaleX(1); }\n'
    + '    25%  { transform: scaleX(0.2); }\n'
    + '    50%  { transform: scaleX(1); }\n'
    + '    75%  { transform: scaleX(0.2); }\n'
    + '    100% { transform: scaleX(1); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes flagDrop {\n'
    + '    0%   { transform: translateY(-100%); }\n'
    + '    100% { transform: translateY(0); }\n'
    + '  }\n'
    + '\n'
    + '  @keyframes blinkText {\n'
    + '    0%, 100% { opacity: 1; }\n'
    + '    50%      { opacity: 0; }\n'
    + '  }\n'
    + '\n'
    + '  /* HUD */\n'
    + '  .coin-hud {\n'
    + '    width: 22px; height: 26px;\n'
    + '    border-radius: 50%;\n'
    + '    background: linear-gradient(135deg, #ffd700, #ffaa00);\n'
    + '    border: 2px solid #c88000;\n'
    + '    display: inline-block;\n'
    + '    vertical-align: middle;\n'
    + '    margin-right: 4px;\n'
    + '    animation: coinSpin 1.2s linear infinite;\n'
    + '  }\n'
    + '\n'
    + '  /* OVERLAY SCENES */\n'
    + '  .overlay-scene {\n'
    + '    position: absolute;\n'
    + '    top: 0;\n'
    + '    left: 0;\n'
    + '    width: ' + WIDTH + 'px;\n'
    + '    height: ' + HEIGHT + 'px;\n'
    + '    z-index: 30;\n'
    + '    display: flex;\n'
    + '    flex-direction: column;\n'
    + '    align-items: center;\n'
    + '    justify-content: center;\n'
    + '    opacity: 0;\n'
    + '    pointer-events: none;\n'
    + '  }\n'
    + '  .overlay-scene.active {\n'
    + '    opacity: 1;\n'
    + '  }\n'
    + '\n'
    + '  /* PHOTO POPUP */\n'
    + '  #photo-popup {\n'
    + '    position: absolute;\n'
    + '    z-index: 40;\n'
    + '    top: ' + (SAFE_TOP + 160) + 'px;\n'
    + '    left: ' + (SAFE_LEFT + 30) + 'px;\n'
    + '    width: ' + (SAFE_RIGHT - SAFE_LEFT - 60) + 'px;\n'
    + '    height: ' + (HEIGHT - SAFE_TOP - SAFE_BOTTOM - 200) + 'px;\n'
    + '    opacity: 0;\n'
    + '    pointer-events: none;\n'
    + '    display: flex;\n'
    + '    align-items: center;\n'
    + '    justify-content: center;\n'
    + '  }\n'
    + '  #photo-popup img {\n'
    + '    width: 100%;\n'
    + '    height: 100%;\n'
    + '    object-fit: cover;\n'
    + '    border: 8px solid #FAA005;\n'
    + '    box-shadow: 6px 6px 0 rgba(0,0,0,0.5), 0 0 0 4px #885808;\n'
    + '  }\n'
    + '  #photo-popup.show {\n'
    + '    opacity: 1;\n'
    + '    animation: photoExpand 0.5s ease-out forwards;\n'
    + '  }\n'
    + '  #photo-popup.hide {\n'
    + '    animation: photoShrink 0.3s ease-in forwards;\n'
    + '  }\n'
    + '\n'
    + '  /* POWER-UP ITEMS */\n'
    + '  .powerup-item {\n'
    + '    position: absolute;\n'
    + '    z-index: 35;\n'
    + '    opacity: 0;\n'
    + '    display: flex;\n'
    + '    flex-direction: column;\n'
    + '    align-items: center;\n'
    + '    gap: 16px;\n'
    + '  }\n'
    + '  .powerup-item.rise {\n'
    + '    animation: powerUpRise 0.7s ease-out forwards;\n'
    + '  }\n'
    + '  .mushroom {\n'
    + '    width: 120px; height: 120px;\n'
    + '    position: relative;\n'
    + '  }\n'
    + '  .mushroom-cap {\n'
    + '    width: 120px; height: 60px;\n'
    + '    background: #ff0000;\n'
    + '    border-radius: 60px 60px 0 0;\n'
    + '    border: 5px solid #800000;\n'
    + '    position: relative;\n'
    + '    overflow: hidden;\n'
    + '  }\n'
    + '  .mushroom-cap::before {\n'
    + '    content: "";\n'
    + '    position: absolute;\n'
    + '    top: 10px; left: 20px;\n'
    + '    width: 30px; height: 30px;\n'
    + '    background: #fff;\n'
    + '    border-radius: 50%;\n'
    + '  }\n'
    + '  .mushroom-cap::after {\n'
    + '    content: "";\n'
    + '    position: absolute;\n'
    + '    top: 8px; right: 18px;\n'
    + '    width: 24px; height: 24px;\n'
    + '    background: #fff;\n'
    + '    border-radius: 50%;\n'
    + '  }\n'
    + '  .mushroom-stem {\n'
    + '    width: 70px; height: 60px;\n'
    + '    background: #f8d8b0;\n'
    + '    border: 5px solid #c88000;\n'
    + '    margin: 0 auto;\n'
    + '    border-radius: 0 0 10px 10px;\n'
    + '  }\n'
    + '\n'
    + '  .fireflower {\n'
    + '    width: 100px; height: 120px;\n'
    + '    position: relative;\n'
    + '  }\n'
    + '  .flower-head {\n'
    + '    width: 80px; height: 80px;\n'
    + '    position: relative;\n'
    + '    margin: 0 auto;\n'
    + '  }\n'
    + '  .flower-petal {\n'
    + '    width: 36px; height: 36px;\n'
    + '    background: #ff6600;\n'
    + '    border: 3px solid #cc3300;\n'
    + '    border-radius: 50%;\n'
    + '    position: absolute;\n'
    + '  }\n'
    + '  .flower-center {\n'
    + '    width: 30px; height: 30px;\n'
    + '    background: #ffd700;\n'
    + '    border: 3px solid #c88000;\n'
    + '    border-radius: 50%;\n'
    + '    position: absolute;\n'
    + '    top: 50%; left: 50%;\n'
    + '    transform: translate(-50%, -50%);\n'
    + '    z-index: 1;\n'
    + '  }\n'
    + '  .flower-stem {\n'
    + '    width: 14px; height: 50px;\n'
    + '    background: #00a800;\n'
    + '    border: 3px solid #005800;\n'
    + '    margin: 0 auto;\n'
    + '  }\n'
    + '\n'
    + '  .star {\n'
    + '    width: 110px; height: 110px;\n'
    + '    position: relative;\n'
    + '  }\n'
    + '  .star-body {\n'
    + '    width: 100px; height: 100px;\n'
    + '    background: #ffd700;\n'
    + '    border: 5px solid #c88000;\n'
    + '    clip-path: polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%);\n'
    + '    margin: 0 auto;\n'
    + '  }\n'
    + '  .star-eyes {\n'
    + '    position: absolute;\n'
    + '    top: 40px; left: 50%;\n'
    + '    transform: translateX(-50%);\n'
    + '    width: 40px;\n'
    + '    display: flex;\n'
    + '    justify-content: space-between;\n'
    + '  }\n'
    + '  .star-eye {\n'
    + '    width: 10px; height: 12px;\n'
    + '    background: #000;\n'
    + '    border-radius: 50%;\n'
    + '  }\n'
    + '\n'
    + '  .powerup-label {\n'
    + '    font-size: 34px;\n'
    + '    font-weight: 900;\n'
    + '    color: #fff;\n'
    + '    text-shadow: 3px 3px 0 #000;\n'
    + '    letter-spacing: 3px;\n'
    + '    text-transform: uppercase;\n'
    + '    text-align: center;\n'
    + '    white-space: nowrap;\n'
    + '  }\n'
    + '\n'
    + '  /* FLAGPOLE */\n'
    + '  .flagpole {\n'
    + '    position: absolute;\n'
    + '    z-index: 7;\n'
    + '  }\n'
    + '  .flagpole-pole {\n'
    + '    width: 12px;\n'
    + '    background: #888;\n'
    + '    border: 2px solid #555;\n'
    + '    margin: 0 auto;\n'
    + '  }\n'
    + '  .flagpole-ball {\n'
    + '    width: 28px; height: 28px;\n'
    + '    background: #00a800;\n'
    + '    border: 3px solid #005800;\n'
    + '    border-radius: 50%;\n'
    + '    margin: 0 auto;\n'
    + '  }\n'
    + '  .flagpole-flag {\n'
    + '    width: 80px; height: 60px;\n'
    + '    background: #00a800;\n'
    + '    border: 3px solid #005800;\n'
    + '    position: absolute;\n'
    + '    top: 28px; left: 16px;\n'
    + '  }\n'
    + '\n'
    + '</style>\n'
    + '</head>\n'
    + '<body>\n'
    + '<div id="root">\n'
    + '\n'
    + '  <!-- HUD (always visible, on top of everything) -->\n'
    + '  <div id="hud" style="position:absolute;top:' + SAFE_TOP + 'px;left:' + SAFE_LEFT + 'px;right:' + (WIDTH - SAFE_RIGHT) + 'px;z-index:50;padding:8px 0;">\n'
    + '    <div style="display:flex;justify-content:space-between;align-items:flex-start;font-size:17px;letter-spacing:3px;text-transform:uppercase;color:#fff;text-shadow:2px 2px 0 #000;">\n'
    + '      <div style="text-align:center;">\n'
    + '        <div style="font-size:14px;color:#fff;">AIDAN</div>\n'
    + '        <div id="hud-score" style="font-size:17px;font-weight:700;">000000</div>\n'
    + '      </div>\n'
    + '      <div style="text-align:center;">\n'
    + '        <div style="font-size:14px;">COINS</div>\n'
    + '        <div style="font-size:17px;font-weight:700;"><span class="coin-hud"></span>x<span id="hud-coins">00</span></div>\n'
    + '      </div>\n'
    + '      <div style="text-align:center;">\n'
    + '        <div style="font-size:14px;">WORLD</div>\n'
    + '        <div style="font-size:17px;font-weight:700;">1-1</div>\n'
    + '      </div>\n'
    + '      <div style="text-align:center;">\n'
    + '        <div style="font-size:14px;">TIME</div>\n'
    + '        <div id="hud-time" style="font-size:17px;font-weight:700;">400</div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '  </div>\n'
    + '\n'
    + '  <!-- PERSISTENT TITLE — BIG, BOLD, HIGH CONTRAST -->\n'
    + '  <div id="persistent-title" style="position:absolute;top:' + (SAFE_TOP + 58) + 'px;left:' + SAFE_LEFT + 'px;right:' + (WIDTH - SAFE_RIGHT) + 'px;z-index:50;text-align:center;padding:12px 0 14px 0;background:rgba(0,0,0,0.55);border-radius:8px;">\n'
    + '    <span style="font-family:' + MONO + ';font-size:66px;font-weight:900;letter-spacing:3px;text-transform:uppercase;color:#facc15;text-shadow:4px 4px 0 #000, -2px -2px 0 #000, 2px -2px 0 #000, -2px 2px 0 #000, 0 6px 12px rgba(0,0,0,0.7);line-height:1.1;">MANILA FREE<br>PHOTO SHOOT</span>\n'
    + '  </div>\n'
    + '\n'
    + '  <!-- WORLD CONTAINER — scrolls horizontally -->\n'
    + '  <div id="world">\n'
    + '\n'
    + '    <!-- GROUND: rows of big bricks -->\n'
    + '    <div id="ground">\n'
    + '      ' + Array(Math.ceil(WORLD_W / BRICK_SIZE) * Math.ceil(GROUND_HEIGHT / BRICK_SIZE)).fill(0).map(function() { return '<div class="brick"></div>'; }).join('') + '\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- CLOUDS -->\n'
    + '    <div class="cloud" style="top:' + (SAFE_TOP + 100) + 'px;left:100px;">\n'
    + '      <div style="width:200px;height:80px;background:#fff;border-radius:40px;position:relative;">\n'
    + '        <div style="width:100px;height:60px;background:#fff;border-radius:30px;position:absolute;top:-35px;left:20px;"></div>\n'
    + '        <div style="width:130px;height:70px;background:#fff;border-radius:35px;position:absolute;top:-45px;left:55px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="cloud" style="top:' + (SAFE_TOP + 300) + 'px;left:900px;">\n'
    + '      <div style="width:240px;height:90px;background:#fff;border-radius:45px;position:relative;">\n'
    + '        <div style="width:120px;height:70px;background:#fff;border-radius:35px;position:absolute;top:-40px;left:30px;"></div>\n'
    + '        <div style="width:150px;height:80px;background:#fff;border-radius:40px;position:absolute;top:-50px;left:80px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="cloud" style="top:' + (SAFE_TOP + 160) + 'px;left:1800px;">\n'
    + '      <div style="width:180px;height:70px;background:#fff;border-radius:35px;position:relative;">\n'
    + '        <div style="width:90px;height:50px;background:#fff;border-radius:25px;position:absolute;top:-30px;left:40px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="cloud" style="top:' + (SAFE_TOP + 400) + 'px;left:2800px;">\n'
    + '      <div style="width:220px;height:85px;background:#fff;border-radius:42px;position:relative;">\n'
    + '        <div style="width:110px;height:65px;background:#fff;border-radius:32px;position:absolute;top:-38px;left:25px;"></div>\n'
    + '        <div style="width:140px;height:75px;background:#fff;border-radius:37px;position:absolute;top:-48px;left:70px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="cloud" style="top:' + (SAFE_TOP + 200) + 'px;left:4000px;">\n'
    + '      <div style="width:190px;height:75px;background:#fff;border-radius:37px;position:relative;">\n'
    + '        <div style="width:95px;height:55px;background:#fff;border-radius:27px;position:absolute;top:-32px;left:35px;"></div>\n'
    + '        <div style="width:120px;height:65px;background:#fff;border-radius:32px;position:absolute;top:-42px;left:60px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="cloud" style="top:' + (SAFE_TOP + 350) + 'px;left:5200px;">\n'
    + '      <div style="width:250px;height:95px;background:#fff;border-radius:47px;position:relative;">\n'
    + '        <div style="width:125px;height:72px;background:#fff;border-radius:36px;position:absolute;top:-42px;left:35px;"></div>\n'
    + '        <div style="width:155px;height:82px;background:#fff;border-radius:41px;position:absolute;top:-52px;left:85px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- BUSHES -->\n'
    + '    <div class="bush" style="bottom:' + GROUND_HEIGHT + 'px;left:250px;">\n'
    + '      <div style="width:160px;height:60px;background:#00a800;border-radius:50%;border:4px solid #005800;position:relative;">\n'
    + '        <div style="width:80px;height:40px;background:#00a800;border-radius:50%;border:3px solid #005800;position:absolute;top:-20px;left:35px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="bush" style="bottom:' + GROUND_HEIGHT + 'px;left:1600px;">\n'
    + '      <div style="width:200px;height:70px;background:#00a800;border-radius:50%;border:4px solid #005800;position:relative;">\n'
    + '        <div style="width:100px;height:50px;background:#00a800;border-radius:50%;border:3px solid #005800;position:absolute;top:-25px;left:20px;"></div>\n'
    + '        <div style="width:80px;height:40px;background:#00a800;border-radius:50%;border:3px solid #005800;position:absolute;top:-22px;left:90px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="bush" style="bottom:' + GROUND_HEIGHT + 'px;left:3400px;">\n'
    + '      <div style="width:140px;height:55px;background:#00a800;border-radius:50%;border:4px solid #005800;position:relative;">\n'
    + '        <div style="width:70px;height:35px;background:#00a800;border-radius:50%;border:3px solid #005800;position:absolute;top:-18px;left:30px;"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- PIPE 1 -->\n'
    + '    <div class="pipe" id="pipe1" style="bottom:' + GROUND_HEIGHT + 'px;left:500px;">\n'
    + '      <div class="pipe-rim"></div>\n'
    + '      <div class="pipe-body-part" style="height:140px;"></div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- PIPE 2 -->\n'
    + '    <div class="pipe" id="pipe2" style="bottom:' + GROUND_HEIGHT + 'px;left:1400px;">\n'
    + '      <div class="pipe-rim"></div>\n'
    + '      <div class="pipe-body-part" style="height:200px;"></div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- PIPE 3 -->\n'
    + '    <div class="pipe" id="pipe3" style="bottom:' + GROUND_HEIGHT + 'px;left:3800px;">\n'
    + '      <div class="pipe-rim"></div>\n'
    + '      <div class="pipe-body-part" style="height:160px;"></div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- PIPE 4 -->\n'
    + '    <div class="pipe" id="pipe4" style="bottom:' + GROUND_HEIGHT + 'px;left:4600px;">\n'
    + '      <div class="pipe-rim"></div>\n'
    + '      <div class="pipe-body-part" style="height:180px;"></div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- PIPE 5 -->\n'
    + '    <div class="pipe" id="pipe5" style="bottom:' + GROUND_HEIGHT + 'px;left:5400px;">\n'
    + '      <div class="pipe-rim"></div>\n'
    + '      <div class="pipe-body-part" style="height:200px;"></div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- QUESTION BLOCKS — bigger 120px -->\n'
    + '    <div class="qblock" id="qb1" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:200px;">?</div>\n'
    + '    <div class="qblock" id="qb2" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:750px;">?</div>\n'
    + '    <div class="qblock" id="qb3" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:1100px;">?</div>\n'
    + '    <div class="qblock" id="qb4" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:1700px;">?</div>\n'
    + '    <div class="qblock" id="qb5" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:2200px;">?</div>\n'
    + '    <div class="qblock" id="qb6" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:2700px;">?</div>\n'
    + '    <div class="qblock" id="qb7" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:3100px;">?</div>\n'
    + '    <div class="qblock" id="qb8" style="bottom:' + (GROUND_HEIGHT + 250) + 'px;left:3500px;">?</div>\n'
    + '\n'
    + '    <!-- Brick blocks (decoration) -->\n'
    + '    <div style="position:absolute;bottom:' + (GROUND_HEIGHT + 250) + 'px;left:300px;display:flex;z-index:3;">\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '    </div>\n'
    + '    <div style="position:absolute;bottom:' + (GROUND_HEIGHT + 250) + 'px;left:1200px;display:flex;z-index:3;">\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '    </div>\n'
    + '    <div style="position:absolute;bottom:' + (GROUND_HEIGHT + 250) + 'px;left:1850px;display:flex;z-index:3;">\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '    </div>\n'
    + '    <div style="position:absolute;bottom:' + (GROUND_HEIGHT + 250) + 'px;left:2800px;display:flex;z-index:3;">\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n'
    + '    </div>\n'
    + '\n'
    + '    <!-- Staircase near end -->\n'
    + (function() {
        var stairs = '';
        for (var i = 0; i < 8; i++) {
          stairs += '    <div style="position:absolute;bottom:' + (GROUND_HEIGHT + i * BLOCK_SIZE) + 'px;left:' + (6600 + (7 - i) * BLOCK_SIZE) + 'px;display:flex;z-index:4;">\n';
          for (var j = 0; j <= i; j++) {
            stairs += '      <div class="brick" style="width:' + BLOCK_SIZE + 'px;height:' + BLOCK_SIZE + 'px;"></div>\n';
          }
          stairs += '    </div>\n';
        }
        return stairs;
      })()
    + '\n'
    + '    <!-- FLAGPOLE -->\n'
    + '    <div class="flagpole" style="bottom:' + GROUND_HEIGHT + 'px;left:7300px;">\n'
    + '      <div class="flagpole-ball"></div>\n'
    + '      <div class="flagpole-pole" style="height:700px;"></div>\n'
    + '      <div class="flagpole-flag" id="the-flag" style="transform:translateY(-100%);">\n'
    + '        <div style="width:100%;height:100%;background:#00a800;display:flex;align-items:center;justify-content:center;color:#fff;font-size:14px;font-weight:900;text-shadow:1px 1px 0 #005800;">CLEAR</div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '\n'
    + '  </div><!-- /world -->\n'
    + '\n'
    + '  <!-- PHOTO POPUP -->\n'
    + '  <div id="photo-popup">\n'
    + '    <img id="photo-popup-img" src="" alt="" />\n'
    + '  </div>\n'
    + '\n'
    + '  <!-- POWER-UPS -->\n'
    + '  <div class="powerup-item" id="powerup1" style="left:' + (WIDTH/2 - 140) + 'px;top:' + (HEIGHT/2 - 200) + 'px;">\n'
    + '    <div class="mushroom">\n'
    + '      <div class="mushroom-cap"></div>\n'
    + '      <div class="mushroom-stem"></div>\n'
    + '    </div>\n'
    + '    <div class="powerup-label">1. DM ME</div>\n'
    + '  </div>\n'
    + '\n'
    + '  <div class="powerup-item" id="powerup2" style="left:' + (WIDTH/2 - 120) + 'px;top:' + (HEIGHT/2 - 200) + 'px;">\n'
    + '    <div class="fireflower">\n'
    + '      <div class="flower-head">\n'
    + '        <div class="flower-petal" style="top:0;left:50%;transform:translateX(-50%);"></div>\n'
    + '        <div class="flower-petal" style="bottom:0;left:50%;transform:translateX(-50%);"></div>\n'
    + '        <div class="flower-petal" style="top:50%;left:0;transform:translateY(-50%);"></div>\n'
    + '        <div class="flower-petal" style="top:50%;right:0;transform:translateY(-50%);"></div>\n'
    + '        <div class="flower-center"></div>\n'
    + '      </div>\n'
    + '      <div class="flower-stem"></div>\n'
    + '    </div>\n'
    + '    <div class="powerup-label">2. PICK A DATE</div>\n'
    + '  </div>\n'
    + '\n'
    + '  <div class="powerup-item" id="powerup3" style="left:' + (WIDTH/2 - 130) + 'px;top:' + (HEIGHT/2 - 200) + 'px;">\n'
    + '    <div class="star">\n'
    + '      <div class="star-body"></div>\n'
    + '      <div class="star-eyes">\n'
    + '        <div class="star-eye"></div>\n'
    + '        <div class="star-eye"></div>\n'
    + '      </div>\n'
    + '    </div>\n'
    + '    <div class="powerup-label">3. SHOW UP</div>\n'
    + '  </div>\n'
    + '\n'
    + '  <!-- CTA OVERLAY -->\n'
    + '  <div class="overlay-scene" id="scene-cta">\n'
    + '    <div style="background:rgba(0,0,0,0.7);position:absolute;inset:0;z-index:0;"></div>\n'
    + '    <div style="position:relative;z-index:1;display:flex;flex-direction:column;align-items:center;gap:16px;padding:0 ' + (SAFE_LEFT + 30) + 'px;">\n'
    + '\n'
    + '      <div id="cta-clear" style="opacity:0;font-size:52px;font-weight:900;color:#facc15;text-shadow:4px 4px 0 #000;letter-spacing:6px;text-transform:uppercase;text-align:center;margin-top:' + (SAFE_TOP + 80) + 'px;">\n'
    + '        COURSE CLEAR!\n'
    + '      </div>\n'
    + '\n'
    + '      <div id="cta-score" style="opacity:0;font-size:24px;color:#fff;text-shadow:2px 2px 0 #000;letter-spacing:3px;text-align:center;margin-top:8px;">\n'
    + '        TIME BONUS: 5000\n'
    + '      </div>\n'
    + '\n'
    + '      <div id="cta-handle" style="opacity:0;margin-top:30px;text-align:center;">\n'
    + '        <div style="font-size:56px;font-weight:900;color:#fff;text-shadow:5px 5px 0 #000;letter-spacing:4px;">@madebyaidan</div>\n'
    + '        <div style="font-size:24px;color:rgba(255,255,255,0.85);text-shadow:2px 2px 0 #000;margin-top:8px;letter-spacing:2px;">on Instagram.</div>\n'
    + '      </div>\n'
    + '\n'
    + '      <div id="cta-dm" style="opacity:0;margin-top:30px;text-align:center;">\n'
    + '        <div style="display:inline-block;background:#00a800;border:6px solid #005800;padding:20px 56px;box-shadow:5px 5px 0 rgba(0,0,0,0.4);">\n'
    + '          <span style="font-size:38px;font-weight:900;color:#fff;text-shadow:3px 3px 0 #005800;letter-spacing:5px;text-transform:uppercase;">SEND ME A DM</span>\n'
    + '        </div>\n'
    + '      </div>\n'
    + '\n'
    + '      <div id="cta-limited" style="opacity:0;margin-top:20px;text-align:center;">\n'
    + '        <div style="font-size:24px;color:#facc15;text-shadow:2px 2px 0 #000;letter-spacing:3px;text-transform:uppercase;animation:blinkText 1s infinite;">\n'
    + '          LIMITED SPOTS\n'
    + '        </div>\n'
    + '      </div>\n'
    + '\n'
    + '      <div id="cta-ticker" style="opacity:0;margin-top:14px;font-size:20px;color:#fff;text-shadow:2px 2px 0 #000;letter-spacing:3px;">\n'
    + '        SCORE: <span id="final-score">000000</span>\n'
    + '      </div>\n'
    + '\n'
    + '    </div>\n'
    + '  </div>\n'
    + '\n'
    + '</div><!-- /root -->\n'
    + '\n'
    + '<script>\n'
    + '  /* photo data injected */\n'
    + '  var PHOTOS = ' + photoSrcs + ';\n'
    + '\n'
    + '  /* HUD state */\n'
    + '  var coinCount = 0;\n'
    + '  var score = 0;\n'
    + '\n'
    + '  function updateHUD() {\n'
    + '    document.getElementById("hud-coins").textContent = String(coinCount).padStart(2, "0");\n'
    + '    document.getElementById("hud-score").textContent = String(score).padStart(6, "0");\n'
    + '  }\n'
    + '  function addCoin(n) { coinCount += (n || 1); updateHUD(); }\n'
    + '  function addScore(pts) { score += pts; updateHUD(); }\n'
    + '\n'
    + '  /* Timer countdown via setInterval */\n'
    + '  var timeLeft = 400;\n'
    + '  var timerID = setInterval(function() {\n'
    + '    timeLeft = Math.max(0, timeLeft - 2);\n'
    + '    document.getElementById("hud-time").textContent = String(timeLeft);\n'
    + '  }, 120);\n'
    + '\n'
    + '  /* Helper: bounce a question block */\n'
    + '  function bounceBlock(id) {\n'
    + '    var el = document.getElementById(id);\n'
    + '    if (!el) return;\n'
    + '    el.classList.add("bounce");\n'
    + '    setTimeout(function() {\n'
    + '      el.classList.remove("bounce");\n'
    + '      el.classList.add("used");\n'
    + '      el.textContent = "";\n'
    + '    }, 400);\n'
    + '  }\n'
    + '\n'
    + '  /* Helper: spawn coin pop above element */\n'
    + '  function spawnCoinAbove(id) {\n'
    + '    var el = document.getElementById(id);\n'
    + '    if (!el) return;\n'
    + '    var rect = el.getBoundingClientRect();\n'
    + '    var coin = document.createElement("div");\n'
    + '    coin.style.cssText = "position:fixed;z-index:60;width:36px;height:44px;border-radius:50%;background:linear-gradient(135deg,#ffd700,#ffaa00);border:4px solid #c88000;pointer-events:none;";\n'
    + '    coin.style.left = (rect.left + rect.width / 2 - 18) + "px";\n'
    + '    coin.style.top = (rect.top - 10) + "px";\n'
    + '    coin.style.animation = "coinPop 0.6s ease-out forwards";\n'
    + '    document.body.appendChild(coin);\n'
    + '    setTimeout(function() { coin.remove(); }, 700);\n'
    + '  }\n'
    + '\n'
    + '  /* Helper: show photo popup — lingers 1500ms */\n'
    + '  function showPhoto(index, cb) {\n'
    + '    var popup = document.getElementById("photo-popup");\n'
    + '    var img = document.getElementById("photo-popup-img");\n'
    + '    img.src = PHOTOS[index];\n'
    + '    popup.className = "";\n'
    + '    popup.style.opacity = "1";\n'
    + '    popup.className = "show";\n'
    + '    setTimeout(function() {\n'
    + '      popup.className = "hide";\n'
    + '      setTimeout(function() {\n'
    + '        popup.style.opacity = "0";\n'
    + '        popup.className = "";\n'
    + '        if (cb) cb();\n'
    + '      }, 350);\n'
    + '    }, 1500);\n'
    + '  }\n'
    + '\n'
    + '  /* Helper: show power-up */\n'
    + '  function showPowerUp(id, duration) {\n'
    + '    var el = document.getElementById(id);\n'
    + '    if (!el) return;\n'
    + '    el.style.opacity = "1";\n'
    + '    el.classList.add("rise");\n'
    + '    setTimeout(function() {\n'
    + '      el.style.opacity = "0";\n'
    + '      el.classList.remove("rise");\n'
    + '    }, duration || 1500);\n'
    + '  }\n'
    + '\n'
    + '  /* Helper: animate element */\n'
    + '  function animateEl(id, animName, dur) {\n'
    + '    var el = document.getElementById(id);\n'
    + '    if (!el) return;\n'
    + '    el.style.animation = animName + " " + (dur || "0.5s") + " ease-out forwards";\n'
    + '    el.style.opacity = "1";\n'
    + '  }\n'
    + '\n'
    + '\n'
    + '  /* SCENE 2: Question blocks bounce, photos pop — slower spacing */\n'
    + '  var photoTimes = ' + photoTimesJSON + ';\n'
    + '\n'
    + '  photoTimes.forEach(function(t, i) {\n'
    + '    var qbId = "qb" + (i + 1);\n'
    + '    setTimeout(function() {\n'
    + '      bounceBlock(qbId);\n'
    + '      spawnCoinAbove(qbId);\n'
    + '      addCoin();\n'
    + '      addScore(200);\n'
    + '      setTimeout(function() { showPhoto(i); }, 300);\n'
    + '    }, t);\n'
    + '  });\n'
    + '\n'
    + '\n'
    + '  /* SCENE 3: Steps as power-ups */\n'
    + '  setTimeout(function() {\n'
    + '    var world = document.getElementById("world");\n'
    + '    world.style.animationPlayState = "paused";\n'
    + '  }, ' + scene3Start + ');\n'
    + '\n'
    + '  setTimeout(function() {\n'
    + '    showPowerUp("powerup1", 1500);\n'
    + '    addCoin();\n'
    + '    addScore(1000);\n'
    + '  }, ' + (scene3Start + 200) + ');\n'
    + '\n'
    + '  setTimeout(function() {\n'
    + '    showPowerUp("powerup2", 1500);\n'
    + '    addCoin();\n'
    + '    addScore(1000);\n'
    + '  }, ' + (scene3Start + 1800) + ');\n'
    + '\n'
    + '  setTimeout(function() {\n'
    + '    showPowerUp("powerup3", 1500);\n'
    + '    addCoin();\n'
    + '    addScore(1000);\n'
    + '  }, ' + (scene3Start + 3400) + ');\n'
    + '\n'
    + '\n'
    + '  /* SCENE 4: CTA — Course Clear */\n'
    + '  setTimeout(function() {\n'
    + '    var world = document.getElementById("world");\n'
    + '    world.style.animationPlayState = "running";\n'
    + '  }, ' + scene4Start + ');\n'
    + '\n'
    + '  setTimeout(function() {\n'
    + '    var flag = document.getElementById("the-flag");\n'
    + '    if (flag) flag.style.animation = "flagDrop 0.8s ease-out forwards";\n'
    + '  }, ' + (scene4Start + 200) + ');\n'
    + '\n'
    + '  setTimeout(function() {\n'
    + '    document.getElementById("scene-cta").classList.add("active");\n'
    + '\n'
    + '    setTimeout(function() { animateEl("cta-clear", "flashBig", "0.6s"); addScore(5000); }, 200);\n'
    + '    setTimeout(function() { animateEl("cta-score", "fadeIn", "0.4s"); addScore(5000); }, 1000);\n'
    + '    setTimeout(function() { animateEl("cta-handle", "slideUp", "0.5s"); }, 1800);\n'
    + '    setTimeout(function() { animateEl("cta-dm", "popIn", "0.5s"); }, 2800);\n'
    + '    setTimeout(function() { animateEl("cta-limited", "fadeIn", "0.4s"); }, 3400);\n'
    + '    setTimeout(function() {\n'
    + '      animateEl("cta-ticker", "fadeIn", "0.3s");\n'
    + '      document.getElementById("final-score").textContent = String(score).padStart(6, "0");\n'
    + '    }, 4000);\n'
    + '  }, ' + (scene4Start + 500) + ');\n'
    + '\n'
    + '  /* Stop timer */\n'
    + '  setTimeout(function() { clearInterval(timerID); }, ' + (scene4Start + 4500) + ');\n'
    + '\n'
    + '</' + 'script>\n'
    + '</body>\n'
    + '</html>';
}

/* ──────────────────────────────────────
   RENDER
   ────────────────────────────────────── */
async function render() {
  resetOutputDir()

  const imageDataMap = {}
  for (const photo of PROOF_PHOTOS) {
    imageDataMap[photo] = readImage(photo)
  }

  writeSources({
    createdAt: new Date().toISOString(),
    strategy: 'v33d — slower photos (~1.5s), bigger title (66px), bigger blocks (120px), CSS scroll',
    safeBottomPixels: SAFE_BOTTOM,
    photos: PROOF_PHOTOS,
  })

  const browser = await chromium.launch()
  console.log('Recording Mario zoomed-in close-up reel v33d (CSS-only animations)...')

  const videoCtx = await browser.newContext({
    viewport: { width: WIDTH, height: HEIGHT },
    deviceScaleFactor: 1,
    recordVideo: { dir: OUT_DIR, size: { width: WIDTH, height: HEIGHT } }
  })

  const videoPage = await videoCtx.newPage()
  await videoPage.evaluate(() => {
    document.documentElement.style.background = '#5c94fc'
    document.body.style.background = '#5c94fc'
  })

  const html = buildHTML(imageDataMap)
  await videoPage.setContent(html, { waitUntil: 'load' })
  await videoPage.waitForTimeout(500)
  await videoPage.waitForTimeout(TOTAL_DURATION_MS)

  await videoPage.close()
  await videoCtx.close()
  await browser.close()

  const videoFiles = fs.readdirSync(OUT_DIR).filter(f => f.endsWith('.webm'))
  if (videoFiles.length === 0) {
    console.error('No video file was generated!')
    return
  }

  const srcVideo = path.join(OUT_DIR, videoFiles[0])
  const dstVideo = path.join(OUT_DIR, 'manila-mario-v33d.mp4')

  const { execSync } = await import('child_process')
  try {
    execSync(`ffmpeg -y -i "${srcVideo}" -c:v libx264 -pix_fmt yuv420p -r 30 -an "${dstVideo}"`, { stdio: 'pipe' })
    fs.unlinkSync(srcVideo)
    console.log('Rendered manila-mario-v33d.mp4')
  } catch (err) {
    console.warn('ffmpeg conversion issue, trying alternate...', err.message)
    try {
      execSync(`/opt/homebrew/bin/ffmpeg -y -i "${srcVideo}" -c:v libx264 -pix_fmt yuv420p -r 30 -an "${dstVideo}"`, { stdio: 'pipe' })
      fs.unlinkSync(srcVideo)
      console.log('Rendered manila-mario-v33d.mp4 (alt ffmpeg)')
    } catch {
      console.warn('ffmpeg not available, keeping as webm')
      fs.renameSync(srcVideo, dstVideo.replace('.mp4', '.webm'))
    }
  }

  console.log('Done: output written to ' + OUT_DIR)
}

render().catch(error => {
  console.error(error)
  process.exit(1)
})
